name: Python ra_synthesis_job build

on:
  push:
    branches:
      - develop
      - airflow-integration-1-3-0

  # Run test build for any PRs
  pull_request:

env:
  location: eastus

jobs:
  push:
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v1
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl unzip psmisc
          pip install cython==0.29.0 pytest
      - name: Build wheels
        run: |
          ./python/build-wheel-manylinux2014.sh

  # Push image to Package Registry.
#  push:
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        python-version: [3.8]
#    if: github.event_name == 'push'
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install python dependencies
#        run: |
#          python --version
#          python -m pip install --upgrade pip
#          export GEMFURY_PULL_TOKEN=${{secrets.GEMFURY_PULL_TOKEN}}
#          pip install -r requirements.txt
#          pip install -r requirements-dev.txt
#      - name: Lint with flake8
#        run: |
#          flake8 ra_synthesis_job --count  --show-source --statistics
#      - name: Unit Test
#        run: pytest --workers auto tests/unit
#      - name: Build
#        run: |
#          hatch clean
#          python setup.py bdist_egg --exclude-source-files
#          wheel convert dist/*.egg -d dist
#      - name: Push To Gemfury
#        run: |
#          WHL_NAME=$(ls dist/*.whl)
#          curl -F package=@${WHL_NAME} https://${{ secrets.GEMFURY_PUSH_TOKEN }}@push.fury.io/replica-analytics/
